
from podgen import Podcast, Episode, Media
import urllib

from pyquery import PyQuery as pq
from lxml import etree


BASE_URL = "https://www.dhammatalks.org/"
MORNING_TALKS_URL = "https://www.dhammatalks.org/mp3_short_index.html"

p = Podcast(
   name="Short (Morning) Dhamma Talks by Thanissaro Bhikkhu",
   description="""These short Dhamma talks by Thanissaro Bhikkhu were given at Metta Forest Monastery most mornings in both English and Thai. The English portion has been excerpted and offered here for streaming and downloading. The talks last about 3 to 5 minutes.
   Podcast feed generated by nadvornik.jiri@gmail.com.""",
   website="https://www.dhammatalks.org/mp3_short_index.html",
   explicit=False,
)

#soup = bs(urlopen(MORNING_TALKS_URL), "html.parser")
d = pq(url=MORNING_TALKS_URL)

for episode_tag in d('a.audio'):

	inner_span = episode_tag.find("span")
	#embed()
	if inner_span is not None:
		# todo: warning
		inner_span.drop_tree()
	name = urllib.parse.unquote(episode_tag.text_content().strip())
	url = episode_tag.attrib.get("href")
	if url and name:
		url = urllib.parse.urljoin(BASE_URL, url)
		p.episodes += [
		Episode(
		title=name,
		media=Media(url)
		)
	]
	else:
		#todo: warning
		pass

rss = p.rss_str()
print(rss)
